// Generated by https://quicktype.io

class Equipamento {
  int id;
  String brand;
  String dateOfAcquisition;
  int equipCategoryId;
  int laboratoryId;
  int specificationId;

  Equipamento({
    this.id,
    this.brand,
    this.dateOfAcquisition,
    this.equipCategoryId,
    this.laboratoryId,
    this.specificationId,
  });

  Equipamento.fromJson(Map<String,dynamic> json)
    : 
    id=json["id"],
    brand=json["brand"],
    dateOfAcquisition=json["dateOfAcquisition"],
    laboratoryId=json["laboratoryId"],
    specificationId=json["specificationId"];
}
